#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

#use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;
use Symfony\Component\Config\FileLocator;

$container = new Symfony\Component\DependencyInjection\ContainerBuilder();
$loader = new YamlFileLoader($container, new FileLocator(__DIR__ . '/config'));
$loader->load('services.yml');

$command = $container->get('explainer.command');
use Symfony\Component\Console\Application;
$app = new Application('Explainer Console App', 'v1.0.0');
$app->add($command);
$app->run();