services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SmartGamma\MySqlExplainer\:
    resource: '../src/*'
    exclude: '../src/{Document}'

  SmartGamma\MySqlExplainer\Command\ExplainerCommand:
    public: true

  SmartGamma\MySqlExplainer\Command\:
    resource: '../src/Command'
    tags: ['console.command']

  explainer.command:
    class: SmartGamma\MySqlExplainer\Command\ExplainerCommand
    public: true