services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SmartGamma\MySqlExplainer\:
    resource: '../src/SmartGamma/MySqlExplainer/*'

  app:
    class: Symfony\Component\Console\Application
    public: true
    calls:
      - method: add
        arguments:
          - '@SmartGamma\MySqlExplainer\Command\ExplainerCommand'