services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $dbHost: '%dbHost%'
      $dbName: '%dbName%'
      $dbUser: '%dbUser%'
      $dbPassword: '%dbPassword%'
      $logPath: '%logPath%'

  SmartGamma\MySqlExplainer\:
    resource: '../src/SmartGamma/MySqlExplainer/*'

  SmartGamma\MySqlExplainer\Service\Analyzer:
    calls:
      - method: registerProvider
        arguments:
          - '@SmartGamma\MySqlExplainer\Service\AnalyzerProvider\QueryPrinter'
      - method: registerProvider
        arguments:
          - '@SmartGamma\MySqlExplainer\Service\AnalyzerProvider\MySqlDuration'
      - method: registerProvider
        arguments:
          - '@SmartGamma\MySqlExplainer\Service\AnalyzerProvider\MySqlExplain'

  app:
    class: Symfony\Component\Console\Application
    public: true
    calls:
      - method: add
        arguments:
          - '@SmartGamma\MySqlExplainer\Command\ExplainerCommand'